### ISSUE TITLE
Please define a license

### ISSUE THREAD

**Issue by gleber** [sjmackenzie/nix-ejabberd#1]
Please define a license. I am looking into working on packaging erlang libraries in nixpkgs (both for development and deployment) and I need to know if I can make use of the code you've shared in this repository. If possible, MIT, BSD and Apache are preferred by me. Thanks!

**Comment by sjmackenzie** [comment]
Ah yeah - forgot about this project. I prefer share-and-share alike licenses. MPLv2 is a good balance between business and hacker needs.
